replicaCount: 1
image: 
  repository: amish28/go-web-app
  pullPolicy: IfNotPresent
  tag: "15993355417"
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
